version: "3.8"

services:
 mongodb:
  image: mongo
  container_name: mongodb
  volumes:
  - ./mongodb/db:/data/db
  ports:
  - 27017:27017
  restart: unless-stopped
 scraper:
  build: ./scraper
  volumes: 
  - ./scraper:/usr/src/app
  ports: 
  - 80:80
